### ISSUE TITLE
🐛 [수정-메인 페이지] 첫 마운트 시 오브제 목록 미조회

### ISSUE THREAD

**Issue by yoouung** [100-hours-a-week/10-team-joytas-dao-fe#101]
##  버그 설명

- 로그인 후 메인 페이지 첫 접속 시 오브제 목록이 조회되지 않음

## 재현하는 방법

동작을 재현하는 단계:

1. 로그인
2. 메인 페이지 접속

## 예상한 동작

- 오브제 목록 조회

## 스크린샷 

https://github.com/user-attachments/assets/fdc63b56-9527-4e31-bb04-0bdf8b12e520

**Comment by erica0321** [comment]
수정했슴다
