### ISSUE TITLE
🐛 [수정-오브제 수정 페이지] 태그 멤버 리스트에 본인 포함 오류

### ISSUE THREAD

**Issue by yoouung** [100-hours-a-week/10-team-joytas-dao-fe#115]
## 🐛 버그 설명

- 오브제 멤버 태그 리스트에 본인이 포함됨

## ⌨️ 재현하는 방법

1. 내가 만들었던 오브제 상세 조회
2. 오브제 수정 페이지 접속

## 🫧 예상한 동작

- 태그 리스트에 본인 제외 표시

## 📸 스크린샷

<img width="351" alt="image" src="https://github.com/user-attachments/assets/ed06e165-ae1e-435b-91fc-f03117e80f19">

**Comment by erica0321** [comment]
수정했습니다
