### ISSUE TITLE
🐛 [로그인 시] 개발자도구에 에러 출력

### ISSUE THREAD

**Issue by yeji0214** [100-hours-a-week/10-team-joytas-dao-fe#207]
## 🐛 버그 설명

카카오 로그인 시 개발자 도구에 Unauthorized 에러 출력

## ⌨️ 재현하는 방법

1. 카카오 로그인

## 🫧 예상한 동작

에러 발생 X

## 📸 스크린샷

<img width="493" alt="image" src="https://github.com/user-attachments/assets/f3658adc-0f35-4a98-9cd4-65c8555a2828">

**Comment by erica0321** [comment]
해당 콘솔 로그는

**Comment by erica0321** [comment]
정상작동임니다잇~
