### ISSUE TITLE
[맥-크롬-1080-오브제 생성 페이지] 오브제 생성 페이지 URL에 undefined

### ISSUE THREAD

**Issue by yeji0214** [100-hours-a-week/10-team-joytas-dao-fe#89]
##  버그 설명

오브제 생성 페이지 URL에 undefined가 포함되어 있습니다.

## 재현하는 방법

오브제 생성 페이지로 들어갑니다.

## 예상한 동작

undefined가 없는 정상적인 URL로 이동

## 스크린샷 (옵션)

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/d926012b-5266-4f09-ab19-b191940de032">

**Comment by erica0321** [comment]
수정완료했습니답
